name: AboutGUI
version: '1.0'
main: org.guaitech.chunk.plugins.AboutGUI
api-version: '1.20'
authors: [ Stewawa, GuaiZai ]
description: A Minecraft 1.20.4 Paper plugin that displays a graphical help interface, customized for Chunk Server.
commands:
  about:
    description: Show the Help Interface.
    permission: aboutgui.about
permissions:
  aboutgui.about:
    description: 允许使用 /about 命令。
    default: true